# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-14 02:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mana', '0003_newuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewUser',
            new_name='BelongTo',
        ),
    ]
