# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-13 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaflet_storage', '0004_tilelayer_tms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberid', models.BigIntegerField()),
                ('name', models.CharField(max_length=80)),
                ('addr', models.CharField(max_length=100)),
                ('faren', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('homepage', models.CharField(max_length=100)),
                ('addtime', models.DateField()),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='map',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='com', to='leaflet_storage.Company'),
        ),
    ]
