# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-15 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaflet_storage', '0006_auto_20171013_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='company_id',
            field=models.IntegerField(default=0),
        ),
    ]
